export type Language = "en" | "pt";

export const portfolioCopy = {
  en: {
    meta: {
      title: "André Fleischfresser — Developer & Builder",
      description: "The portfolio of André Fleischfresser — software engineering student, developer and builder learning through real projects.",
    },
    navigation: {
      primary: "Primary navigation",
      mobile: "Mobile navigation",
      overview: "Overview",
      gap: "Gap",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
      open: "Open navigation",
      close: "Close navigation",
      language: "Select language",
      english: "English",
      portuguese: "Portuguese",
    },
    hero: {
      eyebrow: "Software Engineering Student · Developer · Builder",
      manifesto: "I enjoy building things, experimenting, and learning by doing.",
      credibility: "Software Engineering @ PUCPR · iOS Automation QA @ Mitel",
      description: "I build software by experimenting, testing ideas, and learning through real projects — from robotics and embedded systems to backend applications, automation and native iOS products.",
      viewWork: "View my work",
      thread: "Follow the thread: experimentation → engineering → reliability → product thinking",
    },
    gap: {
      sectionLabel: "Flagship project",
      kicker: "Native iOS · Product experiment",
      learning: "Product thinking · Iteration",
      tagline: "How much time do I have right now?",
      description: "Gap helps people find tasks that realistically fit their current amount of free time, context and priorities — instead of presenting another large to-do list.",
      viewProject: "View project",
      readCaseStudy: "Read case study",
      closeCaseStudy: "Close case study",
      fullCaseStudy: "Read full case study",
      screens: ["START WITH TIME", "SMART RECOMMENDATION", "CONTEXT & PRIORITY"],
      screenAlts: ["Home screen from Gap", "Smart recommendation screen from Gap", "New task screen from Gap"],
      caseLabel: "Case study · product thinking",
      caseTitle: "From time filtering to less decision friction.",
      caseStory: "5 discovery interviews showed that short free-time gaps create decision friction: people have time, but struggle to choose what realistically fits. To validate that core experience first, Gap intentionally deferred authentication, notifications, widgets, gamification, analytics, calendar integration and AI.",
      explores: "What it explores",
      features: ["5–30 minute time windows", "Contexts and priorities", "Pick for Me recommendations", "Completed history and Time Reclaimed"],
    },
    featured: {
      sectionLabel: "Selected work",
      title: "Selected work.",
      intro: "The work below follows that thread — from architecture and business rules to collaboration and physical experimentation. Each project is a different way of learning by making.",
      repository: "View repository",
      helpDesk: {
        category: "Full stack · backend architecture",
        learning: "Architecture · Business logic",
        description: "A help desk system built around authentication, role-based authorization, ticket CRUD, assignment, status and priority workflows, comments, filtering, pagination, dashboard, validation, automated tests and API documentation.",
        emphasis: "A project about business logic, architecture, testing and maintainability.",
      },
      elderWatch: {
        category: "Collaborative university project · PUCPR",
        learning: "Experimentation · Physical systems",
        description: "An ESP32 prototype focused on elderly safety, exploring fall detection using motion data, an emergency button, sound sensing, Telegram alerts, medication reminders and a local monitoring dashboard.",
        emphasis: "Experimentation at the intersection of hardware and software.",
      },
      promoSearch: {
        category: "Collaborative university project · PUCPR",
        learning: "Collaboration · Full stack",
        description: "A marketplace for local promotions where stores publish offers and customers discover nearby deals through roles, moderation workflows, relational data, browser geolocation, maps and radius/category filtering.",
        emphasis: "A study in turning local context into useful discovery.",
      },
    },
    other: {
      label: "Other projects",
      intro: "Smaller experiments, collaborations and iterations that keep the learning moving.",
      descriptions: [
        "A full stack habit tracker focused on check-ins, streaks, consistency calculation and idempotent operations.",
        "A collaborative university Python project for organizing table-tennis player queues and match history.",
        "A smaller Java/JavaFX desktop implementation related to the PromoSearch concept.",
      ],
    },
    experience: {
      label: "Professional experience",
      period: "Current role",
      title: "iOS Automation QA Intern",
      description: "I work with automated testing for a production iOS application. The work has taught me to think about reliability, maintainability and collaboration in addition to simply making software work.",
      skills: ["Appium & XCUITest", "Cucumber", "Playwright", "UI & end-to-end automation", "Regression testing & debugging", "Git & collaborative development"],
    },
    how: {
      label: "How I build",
      titleStart: "I learn best by",
      titleAccent: "building.",
      intro: "Every project gives me something new to understand, test and carry into the next one. I learn best by building real things, listening closely to what they teach me, and carrying that experience forward.",
      stages: [
        { title: "Robotics & embedded systems", text: "Robotics taught me to experiment with physical systems, where software has to respond to real constraints.", carry: "Learning through experimentation and immediate feedback." },
        { title: "Backend & full stack", text: "Backend development taught me to think in architecture, business rules, data and the contracts between them.", carry: "Thinking in terms of structure, architecture and business rules." },
        { title: "Professional automation", text: "Test automation taught me to care about reliability, maintainability and the edge cases that shape a product.", carry: "Looking for edge cases, reliability and failure modes." },
        { title: "Native iOS & product", text: "Building native iOS apps is teaching me more about product decisions and the relationship between technology and the user.", carry: "Thinking closer to the user and iterating on real product decisions." },
      ],
    },
    milestones: {
      label: "Milestones",
      title: "More than projects.",
      intro: "A couple of milestones that shaped how I learn, lead and build.",
      robotics: "Robotics",
      roboticsAchievement: "2× 2nd place at OBR",
      roboticsDescription: "I worked as a robotics instructor and mentor during my internship, helping prepare and guide a team for the Brazilian Robotics Olympiad.",
      roboticsItems: ["2nd place — OBR Pista", "2nd place — OBR Artística", "Qualified for the national stage in OBR Artística"],
      academic: "Academic",
      academicAchievement: "IRA 91 / 100",
      academicDescription: "Software Engineering · PUCPR",
    },
    exploring: {
      label: "Currently exploring",
      title: "What I’m exploring now.",
      intro: "Where previous projects lead, and what I’m curious about next.",
      directions: [
        { title: "Native iOS & Product", description: "Swift, SwiftUI, native iOS development and product development." },
        { title: "Software Architecture", description: "Software architecture and cloud architecture." },
        { title: "Quality & Reliability", description: "Automated testing and deeper engineering reliability." },
      ],
    },
    contact: {
      label: "Contact",
      title: "Have a good question",
      description: "I’m always interested in thoughtful conversations about products, engineering and what we can learn by making something real.",
      location: "Curitiba, Paraná, Brazil",
      copyEmail: "Copy email",
      copied: "Copied",
      copySuccess: "Email copied to clipboard",
      copyError: "Copy is unavailable — use the email link instead",
    },
    footer: "Built by learning through doing",
  },
  pt: {
    meta: {
      title: "André Fleischfresser — Desenvolvedor & Criador",
      description: "Portfólio de André Fleischfresser — estudante de Engenharia de Software, desenvolvedor e criador que aprende com projetos reais.",
    },
    navigation: {
      primary: "Navegação principal",
      mobile: "Navegação móvel",
      overview: "Visão geral",
      gap: "Gap",
      projects: "Projetos",
      experience: "Experiência",
      contact: "Contato",
      open: "Abrir navegação",
      close: "Fechar navegação",
      language: "Selecionar idioma",
      english: "Inglês",
      portuguese: "Português",
    },
    hero: {
      eyebrow: "Estudante de Engenharia de Software · Desenvolvedor · Criador",
      manifesto: "Gosto de construir coisas, experimentar e aprender na prática.",
      credibility: "Engenharia de Software @ PUCPR · QA de Automação iOS @ Mitel",
      description: "Construo software experimentando, testando ideias e aprendendo com projetos reais — da robótica e sistemas embarcados a aplicações backend, automação e produtos nativos para iOS.",
      viewWork: "Ver projetos",
      thread: "Siga o fio: experimentação → engenharia → confiabilidade → pensamento de produto",
    },
    gap: {
      sectionLabel: "Projeto principal",
      kicker: "iOS nativo · Experimento de produto",
      learning: "Pensamento de produto · Iteração",
      tagline: "Quanto tempo eu tenho agora?",
      description: "Gap ajuda as pessoas a encontrar tarefas que realmente cabem no tempo livre, no contexto e nas prioridades do momento — em vez de apresentar mais uma lista extensa de afazeres.",
      viewProject: "Ver projeto",
      readCaseStudy: "Ler estudo de caso",
      closeCaseStudy: "Fechar estudo de caso",
      fullCaseStudy: "Ler estudo de caso completo",
      screens: ["COMECE PELO TEMPO", "RECOMENDAÇÃO INTELIGENTE", "CONTEXTO & PRIORIDADE"],
      screenAlts: ["Tela inicial do Gap", "Tela de recomendação inteligente do Gap", "Tela de nova tarefa do Gap"],
      caseLabel: "Estudo de caso · pensamento de produto",
      caseTitle: "Da filtragem por tempo a menos atrito na decisão.",
      caseStory: "5 entrevistas de descoberta mostraram que pequenos intervalos livres geram atrito na decisão: as pessoas têm tempo, mas têm dificuldade para escolher o que realmente cabe nele. Para validar primeiro essa experiência central, o Gap adiou intencionalmente autenticação, notificações, widgets, gamificação, análises de uso, integração com calendário e IA.",
      explores: "O que o projeto explora",
      features: ["Janelas de 5–30 minutos", "Contextos e prioridades", "Recomendações do “Escolha por Mim”", "Histórico de tarefas concluídas e tempo recuperado"],
    },
    featured: {
      sectionLabel: "Trabalhos selecionados",
      title: "Trabalhos selecionados.",
      intro: "Os projetos abaixo seguem esse fio — da arquitetura e das regras de negócio à colaboração e à experimentação com sistemas físicos. Cada projeto é uma forma diferente de aprender construindo.",
      repository: "Ver repositório",
      helpDesk: {
        category: "Full stack · arquitetura backend",
        learning: "Arquitetura · Regras de negócio",
        description: "Um sistema de help desk construído em torno de autenticação, autorização por papéis, CRUD de chamados, atribuição, fluxos de status e prioridade, comentários, filtros, paginação, dashboard, validação, testes automatizados e documentação de API.",
        emphasis: "Um projeto sobre regras de negócio, arquitetura, testes e manutenibilidade.",
      },
      elderWatch: {
        category: "Projeto universitário colaborativo · PUCPR",
        learning: "Experimentação · Sistemas físicos",
        description: "Um protótipo com ESP32 voltado à segurança de pessoas idosas, explorando detecção de quedas por dados de movimento, botão de emergência, detecção sonora, alertas via Telegram, lembretes de medicação e um painel local de monitoramento.",
        emphasis: "Experimentação na interseção entre hardware e software.",
      },
      promoSearch: {
        category: "Projeto universitário colaborativo · PUCPR",
        learning: "Colaboração · Full stack",
        description: "Um marketplace de promoções locais em que lojas publicam ofertas e clientes descobrem oportunidades próximas por meio de papéis, fluxos de moderação, dados relacionais, geolocalização do navegador, mapas e filtros por raio e categoria.",
        emphasis: "Um estudo sobre como transformar contexto local em descoberta útil.",
      },
    },
    other: {
      label: "Outros projetos",
      intro: "Experimentos menores, colaborações e iterações que mantêm o aprendizado em movimento.",
      descriptions: [
        "Um habit tracker full stack focado em check-ins, sequências de dias, cálculo de consistência e operações idempotentes.",
        "Um projeto universitário colaborativo em Python para organizar filas de jogadores de tênis de mesa e o histórico de partidas.",
        "Uma implementação desktop menor em Java/JavaFX relacionada ao conceito do PromoSearch.",
      ],
    },
    experience: {
      label: "Experiência profissional",
      period: "Cargo atual",
      title: "Estagiário em QA de Automação iOS",
      description: "Trabalho com testes automatizados para uma aplicação iOS em produção. Essa experiência me ensinou a pensar em confiabilidade, manutenibilidade e colaboração, além de simplesmente fazer o software funcionar.",
      skills: ["Appium & XCUITest", "Cucumber", "Playwright", "Automação de UI & end-to-end", "Testes de regressão & depuração", "Git & desenvolvimento colaborativo"],
    },
    how: {
      label: "Como eu construo",
      titleStart: "Aprendo melhor",
      titleAccent: "construindo.",
      intro: "Cada projeto me dá algo novo para entender, testar e levar para o próximo. Aprendo melhor construindo coisas reais, observando com atenção o que elas me ensinam e levando essa experiência adiante.",
      stages: [
        { title: "Robótica & sistemas embarcados", text: "A robótica me ensinou a experimentar com sistemas físicos, nos quais o software precisa responder a restrições reais.", carry: "Aprender por meio da experimentação e do feedback imediato." },
        { title: "Backend & full stack", text: "O desenvolvimento backend me ensinou a pensar em arquitetura, regras de negócio, dados e nos contratos entre eles.", carry: "Pensar em estrutura, arquitetura e regras de negócio." },
        { title: "Automação profissional", text: "A automação de testes me ensinou a cuidar da confiabilidade, da manutenibilidade e dos casos extremos que moldam um produto.", carry: "Procurar casos extremos, confiabilidade e modos de falha." },
        { title: "iOS nativo & produto", text: "Construir apps nativos para iOS está me ensinando mais sobre decisões de produto e sobre a relação entre tecnologia e usuário.", carry: "Colocar o usuário no centro e iterar sobre decisões reais de produto." },
      ],
    },
    milestones: {
      label: "Marcos",
      title: "Além dos projetos.",
      intro: "Alguns marcos que moldaram a forma como aprendo, lidero e construo.",
      robotics: "Robótica",
      roboticsAchievement: "2× 2º lugar na OBR",
      roboticsDescription: "Atuei como instrutor e mentor de robótica durante meu estágio, ajudando a preparar e orientar uma equipe para a Olimpíada Brasileira de Robótica.",
      roboticsItems: ["2º lugar — OBR Pista", "2º lugar — OBR Artística", "Classificação para a etapa nacional da OBR Artística"],
      academic: "Acadêmico",
      academicAchievement: "IRA 91 / 100",
      academicDescription: "Engenharia de Software · PUCPR",
    },
    exploring: {
      label: "Explorando agora",
      title: "O que estou explorando agora.",
      intro: "Os caminhos abertos pelos projetos anteriores e o que desperta minha curiosidade agora.",
      directions: [
        { title: "iOS nativo & Produto", description: "Swift, SwiftUI, desenvolvimento nativo para iOS e desenvolvimento de produto." },
        { title: "Arquitetura de Software", description: "Arquitetura de software e arquitetura de nuvem." },
        { title: "Qualidade & Confiabilidade", description: "Testes automatizados e aprofundamento em confiabilidade de software." },
      ],
    },
    contact: {
      label: "Contato",
      title: "Tem uma boa pergunta",
      description: "Tenho interesse em conversas sobre produtos, engenharia e sobre como podemos aprender ao construir algo real.",
      location: "Curitiba, Paraná, Brasil",
      copyEmail: "Copiar e-mail",
      copied: "Copiado",
      copySuccess: "E-mail copiado para a área de transferência",
      copyError: "Não foi possível copiar — use o link de e-mail",
    },
    footer: "Feito aprendendo na prática",
  },
} as const;
